import { Poppins } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ScrollToTop from "@/componets/ScrollToTop";
import ClientLayout from "@/componets/clientlayout";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-poppins antialiased`}>
        
        <ToastContainer
          position="top-right"
          autoClose={1500}
        />

        {/* 🔥 IMPORTANT CHANGE */}
        <ClientLayout>
          {children}
        </ClientLayout>

        <ScrollToTop />
      </body>
    </html>
  );
}